Repository spencerwooo/onedrive-cf-index, pull requests merged in 2021-02, with the labels that each got.

#87 feat: sharepoint support 🎉
  src/auth/onedrive.js
  src/config/default.js
  src/folderView.js
  src/index.js
  src/render/htmlWrapper.js
Labels: bug, enhancement, todo

#106 feat: add support for flv preview
  src/fileView.js
  src/render/htmlWrapper.js
Labels: enhancement, todo

#109 feat: update readme with cli usage
  README-CN.md
  README.md
Labels: documentation, enhancement, todo
